[build]
  # Build command for Vite
  command = "npm run build"
  # Output directory
  publish = "dist"

[[redirects]]
  # Redirect all routes to index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache images
  for = "/downloaded_images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
